### PR TITLE
Add support for nRFMicro

### PR DESCRIPTION
**Pull request by pdcook**
## Checklist

- [X] Please provide specific title of the PR describing the change
- [X] If you are adding an new boards, please make sure
  - [X] Provide link to your allocated VID/PID if applicable
  - [X] `UF2_BOARD_ID` in your board.h follow correct format from [uf2 specs](https://github.com/microsoft/uf2#files-exposed-by-bootloaders)

-----------

## Description of Change

Add support for nRFMicro-like boards <https://github.com/joric/nrfmicro/wiki>, such as the extremely popular and affordable SuperMini. Very similar to nice!nano v2 config, but not identical.

VID/PID 1209/5284

### CODE REVIEW

**Review by hathach — COMMENTED** [review]
look good, I marked this as draft for now, when PID PR is merged and new pid is push, you can convert it to ready for review again.

**Comment by pdcook** [comment]
VID/PID allocated, ready for review!

**Comment by joric** [comment]
There was a patch here https://gist.github.com/joric/7226eda8d5fdba44bc64d4520825a11d that blinks and supports OTA (maps LED to 1.10 and DFU to 1.02) https://github.com/joric/nrfmicro/wiki/Bootloader#nrf52840 looks like this PR doesn't take into account that blue led is at 1.10 not at 0.15.

```diff
 src/boards/pca10056/board.h | 13 +++++++------
 1 file changed, 7 insertions(+), 6 deletions(-)

diff --git a/src/boards/pca10056/board.h b/src/boards/pca10056/board.h
index 92ce3462..bfe13798 100644
--- a/src/boards/pca10056/board.h
+++ b/src/boards/pca10056/board.h
@@ -25,20 +25,21 @@
 #ifndef PCA10056_H
 #define PCA10056_H
 
+#define _PINNUM(port, pin)    ((port)*32 + (pin))
+
 /*------------------------------------------------------------------*/
 /* LED
  *------------------------------------------------------------------*/
-#define LEDS_NUMBER         2
-#define LED_PRIMARY_PIN     13
-#define LED_SECONDARY_PIN   14
-#define LED_STATE_ON        0
+#define LEDS_NUMBER       1
+#define LED_PRIMARY_PIN   _PINNUM(1, 10) // Blue
+#define LED_STATE_ON      1
 
 /*------------------------------------------------------------------*/
 /* BUTTON
  *------------------------------------------------------------------*/
 #define BUTTONS_NUMBER      2
-#define BUTTON_1            11
-#define BUTTON_2            12
+#define BUTTON_1            _PINNUM(1,2)
+#define BUTTON_2            _PINNUM(0,12)
 #define BUTTON_PULL         NRF_GPIO_PIN_PULLUP
 
 //--------------------------------------------------------------------+
```

Also see OTA section https://github.com/joric/nrfmicro/wiki/Bootloader#ota-updates "You'd need to short two pins to ground, 0.12 is FRST and 0.11 is DFU in pca10056. Mind that 0.11 does not exist on E73 module so it would need fixing and recompiling the bootloader (e.g. put DFU button BUTTON_1 to pin 1.02 in pca10056/board.h)." I'm not quite sure it does that either.

But the LED is the main issue, I mean what's the point in changing bootloader if it doesn't even support user LED.

**Comment by pdcook** [comment]
Whoops, committed the completely wrong file. My setup is currently a mess. Should be fixed now. I elected to go with the 1.02/0.12 configuration as it appeared that the wiki preferred that.

**Comment by joric** [comment]
LGTM now.

**Comment by fanoush** [comment]
Hi found this PR when searching for SuperMini,  but looks like I am at wrong place as this PR is not for SuperMini @pdcook maybe you can rename the PR title - remove SuperMini from the name?

**Comment by pdcook** [comment]
@fanoush You're right, I'll do that. If you're still looking for a SuperMini bootloader (and Arduino core) you can find that here: https://github.com/pdcook/nRFMicro-Arduino-Core

**Comment by fanoush** [comment]
Thanks. It comes with older version of this bootlader for nice!nano so  it seems I can use  update-nice_nano_bootloader-0.8.3_nosd.uf2 to upgrade.

Came from https://circuitpython.org/board/supermini_nrf52840/ which suggests upgrading bootloader and that page is specifically for SuperMini (there is also separate page for nice!nano https://circuitpython.org/board/nice_nano/ ) but then in the release files there is no file for supermini, so I checked pull requests and found this.

**Review by hathach — APPROVED** [review]
look good now, thank you for the PR

**Pull request merged**
