### PR TITLE
a step to no softdevice

### PR DESCRIPTION
**Pull request by xiongyihui**
Make the bootloader work without softdevice.

comment out https://github.com/adafruit/Adafruit_nRF52_Bootloader/blob/master/Makefile#L245 to enable it.

```
# CFLAGS += -DSOFTDEVICE_PRESENT
```

The MBR at 0x0 to 0x1000 is still required.

### CODE REVIEW

**Comment by hathach** [comment]
related to #30  #74

**Comment by hathach** [comment]
thanks for your PR, however, we haven't decided if we want to have SD-independent bootloader yet. Meanwhile this PR will be pending until we make up our mind.

**Comment by jrobeson** [comment]
@hathach : newer sdks include almost all of this PR out of the box, so SD free bootloader is almost free code wise (but perhaps not support wise)

**Comment by hathach** [comment]
@jrobeson since we have plan to extensive use OTA in the future which requires SD. We don't want an incompatible  bootloader code and Softdevice (e.g v6, v7). And then we have to document which bootloader version work with which Softdevice. Worse an incompatible Softdevice (flashed from previously compatible) can potentially brick device. So we like to keep it as a combo for now, until there is a real reason to separate them.

**Pull request merged**
