### PR TITLE
Add new board PillBug

### PR DESCRIPTION
**Pull request by kylemccreery**

### CODE REVIEW

**Review by hathach — COMMENTED** [review]
thank you for PR, would you mind providing link or explain how you obtain the vid/pid

**Comment by kylemccreery** [comment]
@hathach PID is purchased through MCS Electronics.

**Comment by kylemccreery** [comment]
pid


This is the only way of verifying it that they can provide since they do not do publicly facing databases. I have edited out the address used with the purchase.

**Review by hathach — APPROVED** [review]
thank you for the response, it look great now

**Pull request merged**
